export type WinMode = 'STANDARD' | 'HORIZONTAL' | 'VERTICAL' | 'DIAGONAL' | 'X' | 'BLACKOUT';

export interface BingoCellData {
  id: string;
  text: string;
  isFreeSpace?: boolean;
}

export const BINGO_PROMPTS = [
  // Classics & General Tropes
  "Eleven gets a nosebleed",
  "Dustin uses a radio metaphor",
  "Joyce looks frantic",
  "Hopper uses a gun",
  "80s pop song plays",
  "Lights flicker ominously",
  "Jonathan takes a photo",
  "Demogorgon screeches",
  "Upside Down mentioned",
  "Max floats or is seen",
  "Robin makes a sarcastic quip",
  "Murray drinks vodka",
  "Someone yells 'MIKE!'",
  "Mind Flayer shadow appears",
  "D&D reference made",
  "Steve's hair mentioned",
  "Eddie Munson flashback",
  "Boys riding bikes",
  "Argyle says 'My dudes'",
  "Russian subplot mention",
  "Eggos appear",
  "Flashback to Season 1",
  "Walkie-talkie static",
  "Someone is tied up",
  "Telekinetic scream",
  "New monster revealed",
  "Gate opening visuals",
  "Someone cries",
  "Brenner mentioned",

  // Specific Season 5 Predictions
  "Lucas reads to Max",
  "Will’s neck hair prickles",
  "Steve gets beaten up one last time",
  "Eleven’s nose bleeds from maximum effort",
  "A 'New' 80s hit goes viral",
  "Nancy chooses herself (No Boyfriend ending)",
  "Joyce & Hopper finally have their 'date'",
  "A major Season 1 main character dies",
  "Flashback: 'Look how far they've come'",
  "Mike gives 'Heart of the Party' speech",
  "Erica saves the day or calls them 'Nerds'",
  "Upside Down is permanently frozen/destroyed",
  "A 'dead' character returns in a vision",
  "Robin gets a definitive happy ending",
  "Jonathan takes a final photo of the group",
  "Eleven says 'Friends don't lie'",
  "Ted Wheeler acknowledges the supernatural",
  "Steve’s 'Mom' instincts kick in",
  "Vecna’s clock chimes for the final time",
  "Series ends with Party playing D&D",
  "Holly Wheeler is used as a pawn by Vecna",
  "Vecna performs 'Finger Tilt' telekinesis",
  "Military attempts to firebomb Upside Down",
  "Max finally wakes up",
  "Eleven loses her powers (Human ending)",
  "Steve mentions his '6 nuggets' dream",
  "Will is revealed as 'Final Key' to Vecna",
  "Dr. Owens sacrifices himself",
  "A character loses a limb (Star Wars trope)",
  "Henry Creel's full origin explained",
  "Hopper uses a legendary weapon (Sword/Axe)",
  "Barrier between worlds collapses",
  "The Creel House is demolished",
  "Mike connects to Eleven's mind",
  "Dustin makes a tribute to Eddie",
  "Suzie hacks a government database",
  "Significant time jump to the future",
  "Mind Flayer takes physical form",
  "Code Red called for final battle",
  "Eleven screams to close the mega-rift",
  "Steve & Robin 'heart to heart' in danger",
  "Nancy uses a shotgun or high-caliber rifle",
  "Will’s painting explains how to win",
  "Lucas uses slingshot for pivotal distraction",
  "Mr. Clarke explains the 'Physics of the End'",
  "Heartfelt 'Bro' moment: Steve & Dustin",
  "A wedding or engagement (Jopper?)",
  "Eleven’s buzzcut returns",
  "The 'Brenner' trauma is resolved",
  "NeverEnding Story theme referenced",
  "The Party breaks up for college",
  "Vecna’s physical body found in real world",
  "The Gate is sealed forever",
  "Upside Down changes color (Blue/Gold)",
  "Mike is referred to as the 'Paladin'",
  "Hopper gets 'Coffee and Contemplation'",
  "Ted Wheeler sleeps through apocalypse",
  "Murray uses flamethrowers or karate",
  "Dustin’s 'Suzi-Poo' nickname used",
  "Eleven discovers new 80s food she loves",
  "Robin's 'word vomit' in tense moment",
  "Montage showing fate of every character",
  "Dustin yells 'Son of a Bitch!'",
  "Hopper wears Hawaiian shirt variation",
  "Vecna gets 'roasted' by Erica",
  "Classic 80s movie parodied in battle",
  "Steve’s Winnebago dream mentioned",
  "Eleven says 'Bitchin''",
  "Kids look noticeably like adults (Meta)",
  "Walkman/Cassette destroyed or dies",
  "Finale runtime confirmed 2.5+ hours",
  "Last shot: Black Screen with a sound"
];

export const WIN_PATTERNS = {
  STANDARD: "Standard (Any Line)",
  HORIZONTAL: "Horizontal Only",
  VERTICAL: "Vertical Only",
  DIAGONAL: "Diagonal Only",
  X: "The 'X' Shape",
  BLACKOUT: "Blackout (Full Card)"
};